ci: utiliza Codacy em lugar do Qodana para análise de código e de coverage

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -33,32 +33,58 @@ jobs:
       run: |
         docker compose up -d --build postgres-test api-test && docker compose wait api-test
 
-    - run: echo "Tests returned exit code 0 (Passed)"
+    - run: echo "Tests returned exit code $? (Passed)"
     - name: Ending container
       run: docker compose down
 
-    - name: Copying source code files
-      run: |
-        sudo mkdir -p PYTHON/py
-        sudo cp -r backend/ PYTHON/py/
-
-    - run: |
-        echo "PYTHON/py folder"
-        ls ./PYTHON/py
-    - name: Archive coverage data
-      uses: actions/upload-artifact@v2
+    - name: codacy-coverage-reporter
+      uses: codacy/codacy-coverage-reporter-action@v1
       with:
-        name: py-coverage-data
-        path: ./PYTHON/py/.qodana/code-coverage
-
-    - name: Use Qodana
-      uses: JetBrains/qodana-action@v2023.3
-      env:
-        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # read the steps about it below
+        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
+        # or
+        # api-token: ${{ secrets.CODACY_API_TOKEN }}
+        coverage-reports: .coverage/coverage.xml 
+        # or a comma-separated list for multiple reports
+        # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
+    - name: Run Codacy Analysis CLI
+      uses: codacy/codacy-analysis-cli-action@master
       with:
-        args: "-i,PYTHON/py,--linter,jetbrains/qodana-python-community:2023.3,-u,root"
-        pr-mode: false
-        
+        output: results.sarif
+        format: sarif
+        # Adjust severity of non-security issues
+        gh-code-scanning-compat: true
+        # Force 0 exit code to allow SARIF file generation
+        # This will hand over control about PR rejection to the GitHub side
+        max-allowed-issues: 2147483647
+      
+    # Upload the SARIF file generated in the previous step
+    - name: Upload SARIF results file
+      uses: github/codeql-action/upload-sarif@main
+      with:
+        sarif_file: results.sarif
+
+    # - name: Copying source code files
+    #   run: |
+    #     sudo mkdir -p PYTHON/py
+    #     sudo cp -r backend/ PYTHON/py/
+
+    # - run: |
+    #     echo "PYTHON/py folder"
+    #     ls ./PYTHON/py
+    # - name: Archive coverage data
+    #   uses: actions/upload-artifact@v2
+    #   with:
+    #     name: py-coverage-data
+    #     path: ./PYTHON/py/.qodana/code-coverage
+
+    # - name: Use Qodana
+    #   uses: JetBrains/qodana-action@v2023.3
+    #   env:
+    #     QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} # read the steps about it below
+    #   with:
+    #     args: "-i,PYTHON/py,--linter,jetbrains/qodana-python-community:2023.3,-u,root"
+    #     pr-mode: false
+    #     
   push_to_registry:
 
     name: Push Docker image
